# Generated by Django 3.1.4 on 2021-01-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brompoker', '0002_auto_20201225_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('game_id', models.IntegerField()),
                ('game_name', models.CharField(max_length=128)),
                ('user_id', models.IntegerField()),
                ('user_username', models.CharField(max_length=150)),
                ('chip_delta', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='clubmembership',
            options={'verbose_name': 'Club Membership', 'verbose_name_plural': 'Club Memberships'},
        ),
    ]
