# Generated by Django 3.1.4 on 2021-01-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brompoker', '0003_auto_20210103_0314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
